baseURL = "https://fervent-edison-1c3e4e.netlify.com/"
languageCode = "en-us"
title = "Arpan Vaidya"
theme = "beautifulhugo"
googleAnalytics = "UA-165253846-1"

[Author]
  name = "Arpan Vaidya"
  website = "arpanvaidya.com"
  email = "arpan.vaidya.tech@gmail.com"
  github = "arpanoid"
  linkedin = "arpan-vaidya-20ab521a"

[Params]
  subtitle = ""
  logo = "img/testpattern.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "pages/about/"
    weight = 3

[[menu.main]]
    name = "Projects"
    url = "pages/projects/"
    weight = 3    

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 4