baseurl = "https://fervent-edison-1c3e4e.netlify.com/"
DefaultContentLanguage = "en"
title = "Arpan Vaidya"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentOptions = "linenos=table"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = ""
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Arpan Vaidya"
  website = "arpanvaidya.com"
  email = "arpan.vaidya.tech@domain.com"
  github = "arpanoid"
  linkedin = "arpan-vaidya-20ab521a"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Projects"
    url = "page/projects/"
    weight = 3    

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 4

[context.production.environment]
  HUGO_VERSION = "0.20"
